{{ range $key,$value := .Values.applications}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$key}}-service
  labels:
    app: {{$key}}
spec:
  type: ClusterIP
  selector:
    app: {{$key}}
  ports:
    - protocol: TCP
      port: {{ $value.service.port }}
      targetPort: {{ $value.port }}
{{ end }}